#application.yml


---
server:
  port: 8080
  tomcat:
    use-relative-redirects: true

#로컬 환경.
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:h2:mem:testdb;MODE=Oracle
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

jwt:
  issuer: surfer.com
  secret: qwerasfdqwerasxdkjsadfijo1234124
#  1시간: 3600000
  access-token-validity-in-second: 3600000
  refresh-token-validity-in-second: 3600000

logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: DEBUG
